version: "3"

services:

  # ============================================================
  # HADOOP NAMENODE
  # ============================================================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode-cloud
    hostname: namenode
    restart: unless-stopped
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_cloud_data:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      HDFS_CONF_dfs_webhdfs_enabled: "true"
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_replication: "1"
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
    networks:
      - hadoop-cloud-net

  # ============================================================
  # HADOOP DATANODE 1
  # ============================================================
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1-cloud
    hostname: datanode1
    restart: unless-stopped
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - datanode1_cloud_data:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      HDFS_CONF_dfs_webhdfs_enabled: "true"
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_replication: "1"
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
    networks:
      - hadoop-cloud-net

  # ============================================================
  # HADOOP DATANODE 2
  # ============================================================
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2-cloud
    hostname: datanode2
    restart: unless-stopped
    depends_on:
      - namenode
    ports:
      - "9865:9864"
    volumes:
      - datanode2_cloud_data:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      HDFS_CONF_dfs_webhdfs_enabled: "true"
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_replication: "1"
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
    networks:
      - hadoop-cloud-net

  # ============================================================
  # HADOOP DATANODE 3
  # ============================================================
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3-cloud
    hostname: datanode3
    restart: unless-stopped
    depends_on:
      - namenode
    ports:
      - "9866:9864"
    volumes:
      - datanode3_cloud_data:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      HDFS_CONF_dfs_webhdfs_enabled: "true"
      HDFS_CONF_dfs_permissions_enabled: "false"
      HDFS_CONF_dfs_replication: "1"
      HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: "false"
    networks:
      - hadoop-cloud-net

  # ============================================================
  # YARN RESOURCE MANAGER
  # ============================================================
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager-cloud
    hostname: resourcemanager
    restart: unless-stopped
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
      MAPRED_CONF_mapreduce_framework_name: yarn
    networks:
      - hadoop-cloud-net

  # ============================================================
  # YARN NODE MANAGER
  # ============================================================
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager-cloud
    hostname: nodemanager
    restart: unless-stopped
    depends_on:
      - resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9865 datanode3:9866 resourcemanager:8088"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
      MAPRED_CONF_mapreduce_framework_name: yarn
    networks:
      - hadoop-cloud-net

  # ============================================================
  # YARN HISTORY SERVER
  # ============================================================
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver-cloud
    hostname: historyserver
    restart: unless-stopped
    depends_on:
      - resourcemanager
    ports:
      - "19888:19888"
    volumes:
      - historyserver_cloud_data:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9870 resourcemanager:8088"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      CORE_CONF_hadoop_http_staticuser_user: root
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
      MAPRED_CONF_mapreduce_framework_name: yarn
    networks:
      - hadoop-cloud-net

  # ============================================================
  # SPARK MASTER
  # ============================================================
  spark-master-cloud:
    image: apache/spark:4.1.3-scala2.13-java17-python3-r-ubuntu
    container_name: spark-master-cloud
    hostname: spark-master-cloud
    restart: unless-stopped
    ports:
      - "7077:7077"
      - "8080:8080"
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master-cloud
      - --port
      - "7077"
      - --webui-port
      - "8080"
    networks:
      - hadoop-cloud-net


  # ============================================================
  # SPARK WORKER
  # ============================================================
  spark-worker-cloud:
    image: apache/spark:4.1.3-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-cloud
    hostname: spark-worker-cloud
    restart: unless-stopped
    depends_on:
      - spark-master-cloud
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master-cloud:7077
    networks:
      - hadoop-cloud-net

  # ============================================================
  # JUPYTER WORKSPACE
  # ============================================================
  jupyter-workspace-cloud:
    image: quay.io/jupyter/all-spark-notebook:latest
    container_name: jupyter-workspace-cloud
    hostname: jupyter-workspace-cloud
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      - hadoop-cloud-net

# ============================================================
# PERSISTENT VOLUMES
# ============================================================
volumes:
  namenode_cloud_data:
  datanode1_cloud_data:
  datanode2_cloud_data:
  datanode3_cloud_data:
  historyserver_cloud_data:

# ============================================================
# NETWORK
# ============================================================
networks:
  hadoop-cloud-net:
    driver: bridge